// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/AuthVerify': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/AuthVerify').default>>>>
    }
    '/api/QueryCustomer': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/QueryCustomer').default>>>>
    }
    '/api/TestLogin': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/TestLogin').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
  }
}
export {}